.TH random 1 
.SH NAME
random - a simple utility for generating a random integer
.SH SYNOPSIS
random 

random [num]

random [num1] [num2]
.SH DESCRIPTION
random is a simple utility for generating a random integer.

When run without any arguments, random prints out a random integer between
0 and ULONG_MAX.

When a single argument is provided, if that argument is a valid positive 
integer below ULONG_MAX, random prints out a random integer between 0 and 
the specified integer. If the argument is 0, random prints out a random
integer between 0 and ULONG_MAX.

If two or more arguments are provided, and the first two arguments are valid
positive integers below ULONG_MAX, random prints out a random integer between
the first two arguments.

.SH SEE ALSO
arc4random(3); strtoul(3)
.SH PLATFORMS
random has been tested on MacOS X (x86_64 and M1).
.SH HISTORY
random was written by Sriranga Veeraraghavan <ranga@calalum.org>.
